# -*- coding: utf-8 -*-
{
    'name': 'Salewise Actions',
    'version': '18.0.1.0.0',
    'category': 'Customizations',
    'summary': 'Custom actions for Salewise menus',
    'description': """
        This module provides duplicate actions for Salewise menus,
        allowing independent control over action behavior.
    """,
    'author': 'Salewise',
    'website': 'https://salewise.com',
    'depends': [
        'base',
        'contacts',
        'crm',
        'sale',
        'sale_management',
        'sales_team',
        'account',
        'account_payment_mode',
        'contract',
        'contract_sale',
        'contract_termination',
        'project',
        'documents',
        'calendar',
        'appointment',
        'mail',
        'fetchmail',
        'mass_mailing',
        'utm',
        'link_tracker',
        'social',
        'marketing_automation',
        'hr',
        'hr_contract',
        'hr_holidays',
        'hr_expense',
        'hr_recruitment',
        'hr_skills',
        'payroll',
        'resource',
        'product',
        'base_setup',
        'base_user_role',
        'base_automation',
    ],
    'data': [
        'data/server_actions.xml',
        'data/crm_sales_actions.xml',
        'data/contacts_invoicing_actions.xml',
        'data/project_actions.xml',
        'data/email_actions.xml',
        'data/marketing_actions.xml',
        'data/hr_actions.xml',
        'data/time_expense_actions.xml',
        'data/payroll_actions.xml',
        'data/system_actions.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}