# -*- coding: utf-8 -*-
"""Menu count baseline for SaleWise plans - auto-generated"""

MENU_COUNT_BASELINE = {   'Enterprise': {   'accountant': 82,
                      'admin': 112,
                      'employee': 63,
                      'hr_manager': 81,
                      'hr_officer': 75,
                      'marketing_user': 71,
                      'project_manager': 61,
                      'project_user': 61,
                      'sales_manager': 80,
                      'sales_user': 71,
                      'super_admin': 112,
                      'sys_admin': 103,
                      'team_lead': 78},
    'Professional': {   'accountant': 62,
                        'admin': 82,
                        'employee': 51,
                        'hr_manager': 53,
                        'hr_officer': 52,
                        'marketing_user': 60,
                        'project_manager': 50,
                        'project_user': 50,
                        'sales_manager': 62,
                        'sales_user': 60,
                        'super_admin': 82,
                        'sys_admin': 73,
                        'team_lead': 60},
    'Starter': {   'accountant': 53,
                   'admin': 62,
                   'employee': 42,
                   'hr_manager': 44,
                   'hr_officer': 43,
                   'marketing_user': 43,
                   'project_manager': 41,
                   'project_user': 41,
                   'sales_manager': 53,
                   'sales_user': 51,
                   'super_admin': 62,
                   'sys_admin': 62,
                   'team_lead': 51}}
