# -*- coding: utf-8 -*-
"""Menu count baseline for SaleWise plans - auto-generated"""

MENU_COUNT_BASELINE = {   'Admin': {   'accountant': 82,
                 'admin': 112,
                 'employee': 63,
                 'hr_manager': 81,
                 'hr_officer': 75,
                 'marketing_user': 71,
                 'project_manager': 61,
                 'project_user': 61,
                 'sales_manager': 80,
                 'sales_user': 71,
                 'super_admin': 112,
                 'sys_admin': 103,
                 'team_lead': 78},
    'Enterprise': {   'accountant': 74,
                      'admin': 103,
                      'employee': 63,
                      'hr_manager': 79,
                      'hr_officer': 73,
                      'marketing_user': 71,
                      'project_manager': 61,
                      'project_user': 61,
                      'sales_manager': 74,
                      'sales_user': 67,
                      'super_admin': 103,
                      'sys_admin': 94,
                      'team_lead': 73},
    'Professional': {   'accountant': 54,
                        'admin': 73,
                        'employee': 51,
                        'hr_manager': 51,
                        'hr_officer': 50,
                        'marketing_user': 60,
                        'project_manager': 50,
                        'project_user': 50,
                        'sales_manager': 56,
                        'sales_user': 56,
                        'super_admin': 73,
                        'sys_admin': 64,
                        'team_lead': 55},
    'Starter': {   'accountant': 45,
                   'admin': 53,
                   'employee': 42,
                   'hr_manager': 42,
                   'hr_officer': 41,
                   'marketing_user': 43,
                   'project_manager': 41,
                   'project_user': 41,
                   'sales_manager': 47,
                   'sales_user': 47,
                   'super_admin': 53,
                   'sys_admin': 53,
                   'team_lead': 46}}
