# -*- coding: utf-8 -*-
{
    'name': 'Salewise Bootstrap',
    'version': '18.0.1.0.0',
    'category': 'Technical',
    'summary': 'Bootstrap module for SaleWise',
    'description': """
        SaleWise Bootstrap Module
        =========================
        This module serves as the bootstrap for SaleWise installation.
    """,
    'depends': [
        'account',
        'account_invoice_start_end_dates',
        'account_payment',
        'account_payment_mode',
        'account_payment_partner',
        'analytic',
        'appointment',
        'appointment_crm',
        'appointment_google_calendar',
        'appointment_microsoft_calendar',
        'attachment_indexation',
        'auth_signup',
        'base',
        'base_automation',
        'base_setup',
        'base_sparse_field',
        'base_user_role',
        'bus',
        'calendar',
        'contacts',
        'contract',
        'contract_forecast',
        'contract_forecast_variable_quantity',
        'contract_invoice_auto_validate',
        'contract_invoice_start_end_dates',
        'contract_line_successor',
        'contract_payment_mode',
        'contract_sale',
        'contract_termination',
        'contract_variable_qty_prorated',
        'contract_variable_quantity',
        'crm',
        'digest',
        'documents',
        'google_account',
        'google_calendar',
        'hr',
        'hr_contract',
        'hr_expense',
        'hr_holidays',
        'hr_recruitment',
        'hr_skills',
        'html_editor',
        'http_routing',
        'link_tracker',
        'loyalty',
        'mail',
        'marketing_automation',
        'mass_mailing',
        'microsoft_account',
        'microsoft_calendar',
        'onboarding',
        'payment',
        'payment_stripe',
        'payroll',
        'payroll_account',
        'phone_validation',
        'portal',
        'product',
        'project',
        'queue_job',
        'rating',
        'resource',
        'resource_mail',
        'sale',
        'sale_management',
        'sales_team',
        'social',
        'social_facebook',
        'social_instagram',
        'social_linkedin',
        'social_media',
        'social_twitter',
        'social_youtube',
        'uom',
        'utm',
        'web',
        'web_editor',
        'web_gantt',
        'web_tour',
    ],
    'data': [],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
