{
    'name': 'Salewise Menus',
    'version': '1.0',
    'summary': 'SaaS menu configuration',
    'depends': [
        'base',
        'web',
        'web_tour',  # Added to ensure our patches run after web_tour
        'salewise_actions',  # Custom actions module
        'account',
        'account_payment_mode',
        'appointment',
        'base_automation',
        'base_setup',
        'base_user_role',
        'calendar',
        'contacts',
        'contract',
        'contract_termination',
        'crm',
        'documents',
        'hr',
        'hr_contract',
        'hr_expense',
        'hr_holidays',
        'hr_recruitment',
        'hr_skills',
        'link_tracker',
        'mail',
        'marketing_automation',
        'payroll',
        'product',
        'project',
        'resource',
        'sale',
        'sale_management',
        'sales_team',
        'social',
        'utm',
    ],
    'data': [
        'data/starter_menus.xml',
        'data/enterprise_menus.xml',
        'data/admin_menus.xml',
        'data/professional_menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'salewise_menus/static/src/js/navbar_patch.js',
            'salewise_menus/static/src/js/apps_menu_patch.js',
            'salewise_menus/static/src/xml/apps_menu.xml',
            'salewise_menus/static/src/xml/navbar.xml',
            'salewise_menus/static/src/scss/salewise_menu.scss',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
}